{
    'name': 'Shareholder Management',
    'version': '16.0.0',
    'author': 'Knowledge bonds',
    'website': 'knowledge-bonds.com',
    "depends": ['mail'],
    'data': [
        # 'security/kb_security.xml',
        # 'security/sale_management_security.xml',
        'security/shareholder_management_access_rights.xml',
        'security/ir.model.access.csv',
        'data/kb_data.xml',
        'views/kb_menuitem.xml',
        'views/kb_res_partner_view.xml',
        'views/kb_shareholder_management_view.xml',
        'views/kb_res_company_view.xml',
        'views/sale_managemant.xml',
        'reports/kb_shareholder_management_report.xml',
    ],
    'images': ['static/description/icon.png'],
    'demo': [],
    'installable': True,
    'license': 'LGPL-3',
    'auto_install': False,
    'qweb': [],
    'application': True,
}
