{
    'name': 'Whatsapp-all-in-one Dashboard',
    'version': '16.0.0.0.3',
    'summary': 'Whatsapp-all-in-one Dashboard system',
    'description': 'Conversations Dashboard system',
    'depends': ['base', 'mail', 'base_setup', 'bus', 'web_tour', 'product', 'purchase', 'sale', 'account', 'contacts', 'pragtech_whatsapp_messenger'],
    'data': [#'views/assets.xml',
            #  'views/resconfig.xml',
             'views/pragtech_conversations_dashboard.xml',
             'views/mail_channel_views.xml',
             'security/ir.model.access.csv',
             ],
    'assets': {
        # Custom bundle in case we want to remove things that are later added to web.assets_common
        'mail.assets_common_discuss_public': [
            ('include', 'web.assets_common'),
        ],
        'web.assets_backend': [
            'pragmatic_odoo_whatsapp_integration/static/src/xml/*.xml',
            'pragmatic_odoo_whatsapp_integration/static/src/discuss_sidebar_category_item/discuss_sidebar_category_item.js',
            'pragmatic_odoo_whatsapp_integration/static/src/discuss_sidebar_category/discuss_sidebar_category.js',
            'pragmatic_odoo_whatsapp_integration/static/src/attachment_list/attachment_list.js',
            'pragmatic_odoo_whatsapp_integration/static/src/js/discuss_extend/discuss_component.js',
            'pragmatic_odoo_whatsapp_integration/static/src/js/discuss_extend/widget.js',
            'pragmatic_odoo_whatsapp_integration/static/src/js/discuss_extend/conversations.js',
            'pragmatic_odoo_whatsapp_integration/static/src/js/discuss_extend/container_patch.js',
            'pragmatic_odoo_whatsapp_integration/static/src/autocomplete_input/autocomplete_input.js',
            'pragmatic_odoo_whatsapp_integration/static/src/js/models/thread_add_channel/thread.js',
            'pragmatic_odoo_whatsapp_integration/static/src/js/models/discuss_add_channel/discuss.js',
            'pragmatic_odoo_whatsapp_integration/static/src/models/sidebar_category/*.js',
            'pragmatic_odoo_whatsapp_integration/static/src/message/message.js',
            'pragmatic_odoo_whatsapp_integration/static/src/message/notification_message_view.js',
            'pragmatic_odoo_whatsapp_integration/static/src/message_list/message_list.js',
            'pragmatic_odoo_whatsapp_integration/static/src/list_renderer/basicView.js',
            'pragmatic_odoo_whatsapp_integration/static/src/list_renderer/contactView.js',
            'pragmatic_odoo_whatsapp_integration/static/src/list_renderer/salesView.js',
            'pragmatic_odoo_whatsapp_integration/static/src/list_renderer/purchaseView.js',
            'pragmatic_odoo_whatsapp_integration/static/src/list_renderer/invoicingView.js',
            'pragmatic_odoo_whatsapp_integration/static/src/composer/composer.js',
            'pragmatic_odoo_whatsapp_integration/static/src/composer_text_input/composer_text_input.js',
            'pragmatic_odoo_whatsapp_integration/static/src/list_renderer/list_renderer.js',
            'pragmatic_odoo_whatsapp_integration/static/src/list_renderer/list_controller.js',
            'pragmatic_odoo_whatsapp_integration/static/src/list_renderer/list_view.js',
            'pragmatic_odoo_whatsapp_integration/static/src/thread_view/thread_view.js',
            'pragmatic_odoo_whatsapp_integration/static/src/discuss_sidebar_item/discuss_sidebar_item.js',
            'pragmatic_odoo_whatsapp_integration/static/src/js/discuss_extend/sidebar.js',
            'pragmatic_odoo_whatsapp_integration/static/src/models/messaging_initializer/messaging_initializer.js',
            # 'pragmatic_odoo_whatsapp_integration/static/src/discuss_widget/discuss_widget.xml',
            # 'pragmatic_odoo_whatsapp_integration/static/src/js/discuss_extend/discuss_component.xml',
            'pragmatic_odoo_whatsapp_integration/static/src/**/*.css',
            'pragmatic_odoo_whatsapp_integration/static/src/**/*.scss'
        ],
        'web.assets_common': [
            'pragmatic_odoo_whatsapp_integration/static/lib/js/spectrum.js',
            'pragmatic_odoo_whatsapp_integration/static/lib/js/apexcharts.min.js',
            'pragmatic_odoo_whatsapp_integration/static/lib/js/bootstrap-iconpicker.min.js',
            'pragmatic_odoo_whatsapp_integration/static/lib/js/jquery.ui.touch-punch.min.js',
            'pragmatic_odoo_whatsapp_integration/static/lib/js/gridstack.min.js',
            'pragmatic_odoo_whatsapp_integration/static/lib/js/gridstack.jQueryUI.min.js',
            'pragmatic_odoo_whatsapp_integration/static/lib/css/spectrum.css',
            'pragmatic_odoo_whatsapp_integration/static/lib/css/bootstrap-iconpicker.min.css',
            'pragmatic_odoo_whatsapp_integration/static/lib/css/gridstack.min.css',
            'pragmatic_odoo_whatsapp_integration/static/lib/css/apexcharts.css',
        ],
    },
    'jquery': True,
    'bootstrap': True,
    'demo': [],
    'installable': True,
    'auto-install': False,
    'application': True,
}