{
    'name': 'HR Forms Tahtheeb',
    'version': '16.0.0',
    'author': 'Knowledge bonds',
    'website': 'knowledge-bonds.com',
    'category': 'HR',
    "depends": ['sale_management', 'hr','contacts', 'multi_branch_base', 'hr_contract'],
    'assets': {
        'web.report_assets_common': [
            'kb_hr_tahtheeb/static/scss/custom-font.scss',
        ],
    },
    'data': [
        'security/ir.model.access.csv',
        'views/kb_hr_employee_view.xml',
        'views/kb_hr_forms_reason_view.xml',
        # 'views/kb_hr_contract_view.xml',
        'wizard/kb_hr_forms_wizard_view.xml',
        'reports/kb_experience_certificate_report.xml',
        'reports/kb_end_contract_report.xml',
        'reports/kb_receivables_report.xml',
        'reports/kb_employee_transfer_report.xml',
        'reports/kb_Fixation_salary_Alahly_bank_report.xml',
        'reports/kb_Fixation_salary_French_bank_report.xml',
        'reports/kb_salary_definition_template.xml',
        'reports/kb_employee_offer_template.xml',
        'reports/kb_hr_experience_certificate_report.xml',
        'reports/kb_termination_education_office_contract.xml',
        'reports/kb_report_misconduct_warning_template.xml',
        'reports/kb_regarding_delay.xml',
        'reports/kb_extension_letter_template.xml',
        'reports/kb_job_data_for_contract.xml',
        'reports/kb_salary_adjustment_job_title.xml',
        'reports/kb_contract_termination_form_2024.xml',
        'reports/kb_continuity_desire_statement_2024_approved.xml',
        'reports/internal_header.xml',
        'reports/custom_header.xml',
        'reports/empty_header.xml',
        'reports/confidentiality_agreement_report.xml',
        'reports/administrativ_ job_offer.xml',
        'reports/additional_hours_schools.xml',
        'reports/additional_hours_department.xml',
        'reports/certificate_experience_clearance.xml',

    ],
    'images': ['static/description/icon.png'],
    'demo': [],
    'installable': True,
    'license': 'LGPL-3',
    'auto_install': False,
    'qweb': [],
    'application': True,
}