
{
    'name': 'Schools',
    'version': '1.0.0',
    'author': 'Knowledge bonds',
    'category': 'Extra Tools',
    'sequence': 2240,
    'summary': 'School Managment System',
    'description': """
This module aims to manage Schools
==================================================

Keeps to manage Schools.
       """,
    'website': 'https://www.knowledge-bonds.com',
    'depends': [
        'base',
        'mail',
        'board',
        'hr',
        'website',
        'calendar',
        'report_xlsx',
        'account',
        'website_event',
        'hr_attendance',
        'event',
        'sale',
        'web',
        'rating',
        'website_payment',
        'fleet',
        'contacts',
        'kb_school_withdrawal'
    ],

    'data': [
        # 'security/security.xml',
        # 'security/ir.model.access.csv',

        # 'data/data.xml',
        # # 'data/fees_sq.xml',
        # 'data/activity.xml',

        # 'views/schools.xml',
        # 'views/academic_year.xml', 
        # # 'views/attendance.xml',
        # # 'views/egrade.xml',
        # # 'views/school_grades.xml',
        # 'views/students.xml',
        # 'views/teachers.xml',
        # 'views/parents.xml',
        # 'views/website_form.xml',
        # 'views/class.xml',
        # 'views/subject.xml',
        # # 'views/fees.xml',
        # # 'views/fees_structure.xml',
        # 'views/grade.xml',
        # # 'views/reminder.xml',
        # # 'views/event_view.xml',
        # # 'views/student_assignment.xml',
        # # 'views/teacher_assignment.xml',
        # # 'views/Registrationrequest.xml',
        # # 'views/withdrawal_request_view.xml',
        # # 'views/teachermanege.xml',
        # # 'views/studentassessment.xml',
        # # 'views/school_evaluation_view.xml',
        # 'views/student_assessment_report.xml',
        # # 'views/kb_student_table_view.xml',
        # 'views/yearly_fees.xml',
        # 'views/transport_registration_view.xml',
        # 'views/tran_information_view.xml',
        # # 'views/kb_res_partner_view.xml',
        # # 'views/kb_document_type_view.xml',
        # # 'views/kb_company_details_view.xml',


        # # 'wizard/student_document.xml',
        # # 'wizard/acceptnewstudent.xml',
        # # 'wizard/rejactnewstudent.xml',
        # # 'wizard/acceptcondnewstudent.xml',
        # # 'wizard/hours_work.xml',
        # # 'wizard/add_student_in_grade_view.xml',
        # # 'wizard/reason_wiz_view.xml',
        # # 'wizard/fees_reports_view.xml',
        # 'wizard/kb_transport_wizard_view.xml',
        # 'wizard/kb_attendens_wizard_view.xml',
        # 'wizard/kb_attendance_sheet.xml',
        # 'wizard/kb_attendens_in_school_wizard_view.xml',
        # 'wizard/kb_attendance_in_school_sheet.xml',
        # # 'wizard/StudentReportCardDetailsViwe.xml',

        # # 'report/student_contract_report.xml',
        # 'report/student_card.xml',
        # 'report/teacher_card.xml',
        # 'report/Preparing_students.xml',
        # # 'report/contract_report.xml',
        # # 'report/accounting_and_marketing_report.xml',
        # # 'report/Diploma_registration_contract_Accounting_and_marketing.xml',
        # # 'report/Diploma_registration_contract.xml',
        # # 'report/safety_contract_report.xml',
        # # 'report/withdrawal_request.xml',
        # # 'report/untranscript.xml',
        # # 'report/Transcript.xml',
        # # 'report/teacher_month_report.xml',
        # 'report/report_account_312.xml',
        # 'report/report_account_314.xml',
        # 'report/report_account_315.xml',
        # 'report/Parent_account_statement.xml',
        # 'report/Student_account_statement.xml',
        # 'report/report_teransport_report_view.xml',
        # # 'report/exam_grade_report.xml',
        # # 'report/report_student_academic_report_card.xml',
        # # 'report/report_student_assessment_report_card.xml',
        # # 'report/report_student_trimester_card.xml',
    ],

    'demo': [],
    'assets': {
        'web.assets_backend': [
            # '/kb_Tahtheeb_school/static/src/js/enter_student_marks_client_action.js',
            # '/kb_Tahtheeb_school/static/src/js/grade_marks_client_action.js',
            # '/kb_Tahtheeb_school/static/src/css/school_evaluation.css',
            # 'kb_Tahtheeb_school/static/src/xml/**/*',
            # 'kb_Tahtheeb_school/static/src/components/**/*',

        ],
        'web.assets_qweb': [
            # '/kb_div_school/static/src/xml/display_student_entered_marks_template.xml',
            # '/kb_div_school/static/src/xml/display_grade_marks_template.xml',
        ],
    },
    'installable': True,
    'license': 'LGPL-3',
    'auto_install': False,
    'application': True,
    'qweb': [

    ],
}
