from . import orders
from . import order_line
from . import order_summary
from . import cars
from . import damages_report
from . import damage_tree
from . import goods_transfer
from . import goods_transfer_tree
from . import res_partner
from . import maintenance_table
from . import tires_table
from . import battery_table
from . import employee_fields
from . import dashboard_companies
