{
    'name': 'KB Deduct or Increase Salary',
    'version': '14.0.0',
    'author': 'Knowledge bonds',
    'website': 'knowledge-bonds.com',
    'category': 'HR',
    'summary': 'Deduct or Increase Salary',
    'description': """Deduct or Increase Salary""",
    'depends': [
            'hr',
            'hr_contract',
            'hr_fleet',
            'base',
            'hr_payroll_community',
               ],
    'data': [
        'security/ir.model.access.csv',
        'data/rule.xml',
        'wizard/salary_deduction_view.xml',
        'views/employee_wage1.xml',
        'views/emp_salary_deduct.xml',
        'views/change_reason.xml',
        'views/deduct_increase.xml',
    ],
    'images': ['static/description/icon.png'],
    'demo': [],
    'installable': True,
    'license': 'LGPL-3',
    'auto_install': False,
    'qweb': [],
    'application': True,
}
